config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'events#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :events do
    resources :event_attendances, only: %i[create destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendances, source: :event_attendee

  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true

  scope :past, -> { where('date < ?', Time.current).order(date: :desc) }
  scope :upcoming, -> { where('date >= ?', Time.current).order(:date) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :event_attendances, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def create
    @event_attendance = @event.event_attendances.build(event_attendee: current_user)
    if @event_attendance.save
      redirect_to @event, notice: 'You are new attending this event.'
    else
      redirect_to @event, alert: 'Unable to attend this event.'
    end
  end

  def destroy
    @event_attendance = @event.event_attendances.find_by(event_attendee: current_user)
    if @event_attendance&.destroy
      redirect_to @event, notice: 'You are no longer attending this event.'
    else
      redirect_to @event, alert: 'Unable to cancel attendance.'
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.includes(:attendees).find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<ul>
  <% @events.upcoming.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>

<h1>Past Events</h1>

<ul>
  <% @events.past.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>

<%= link_to "New Event", new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name%>
    <% @event.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date%>
    <% @event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %><br>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p> by: <%= @event.creator.name %></p>
<p><%= @event.date %></p>
<p><%= @event.location %></p>

<%= link_to 'All events', events_path %>

<% if user_signed_in? %>
  <% if @event.attendees.include?(current_user) %>
    <%= button_to 'Cancel Attendance', event_event_attendance_path(@event), method: :delete %>
  <% else %>
    <%= button_to 'Attend Event', event_event_attendances_path(@event), method: :post %>
  <% end %>
<% end %>

<h2>Attendees:</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li>
      <%= link_to attendee.name, attendee %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h2>Created Events</h2>
<ul>
  <% @user.created_events.each do |event| %>
  <li>
    <%= link_to event.name, event %>
  </li>
  <% end %>
</ul>
<h2>Attended Events</h2>

<h3>Upcoming</h3>
<ul>
  <% @user.attended_events.upcoming.find_each do |event| %>
  <li>
    <%= link_to event.name, event %>
  </li>
  <% end %>
</ul>

<h3>Past</h3>
<ul>
  <% @user.attended_events.past.find_each do |event| %>
  <li>
    <%= link_to event.name, event %>
  </li>
  <% end %>
</ul>